# -*- coding: utf-8 -*-
"""ex:powersum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zZbY1-07dODvdJWxSIUdrcK9QtHHxCjy
"""

#Exercise1: Sum up integer powers
def power_sumint(N,i):
  sum=0
  for n in range(1,N+1):
    sum+=(n**i)
  return sum

i=int(input("enter your i value"))
N=int(input("enter your N value"))
sum=power_sumint(N,i)
print("the required sum is",sum)