# -*- coding: utf-8 -*-
"""interacting with python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abCrF-Wr_U68O8quKMoYzkU8iFszfhfY
"""

# introduction of basic pyhton codes

from math import cos, sqrt, pi
cos(pi*sqrt(pi))**7

# %load ../pyfiles/myfirstpy.py
from math import cos, sqrt, pi
print('Hello, I can compute! ')
x = 3
y = cos(pi*sqrt(pi)*x)**7
print('Starting from x =', x, 'we have computed y=', y)

