# -*- coding: utf-8 -*-
"""working with git.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjGrpVeWldtmMZCrxrF9y-VKt2JDfcZq
"""

!pip install gitpython

from git import Repo

# we can query the repository of git through help and use clone_from for different methods

help(Repo.clone_from)

#Classes have a special method called constructor, which you would fnd listed among its
#methods as __init__.

help(Repo.__init__)

# to specify the location we delineate the subfolders by forward slash

coursefolder = '/Users/Jay/tmpdir/'

import os # a module that helps to perfrom task in an independent way
os.path.abspath(coursefolder)

#we now download a course material in Github and store it in mth271content

repodir = os.path.join(os.path.abspath(coursefolder), 'mth271content')
repodir # full path name of the subfolder

# if the folder exist we get true, otherwise false

os.path.isdir(repodir)

if os.path.isdir(repodir): # if repo exists, pull newest data
    repo = Repo(repodir)
    repo.remotes.origin.pull()
else: # otherwise, clone from remote
      repo = Repo.clone_from('https://github.com/jayggg/mth271content',
repodir)

repo.working_dir #variable repodir is stored in a data member called the working_dir.

